<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dropbox - Configuração</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Dropbox - Configuração</h1>
        <div class="row">
            <div class="col-sm-6">
                <form id="dropbox-config-form">
                    <div class="form-group">
                        <label for="app-id">App Id</label>
                        <input type="text" class="form-control" id="app-id" name="app_id" required>
                    </div>
                    <div class="form-group">
                        <label for="app-secret">App Secret</label>
                        <input type="text" class="form-control" id="app-secret" name="app_secret" required>
                    </div>
                    <div class="form-group">
                        <label for="code">Code</label>
                        <input type="text" class="form-control" id="code" name="code" disabled>
                    </div>
                    <button type="submit" class="btn btn-primary">Gerar</button>
                </form>
            </div>
            <div class="col-sm-6">
                <div><strong>Url Autorização:</strong><span id="url-authorization"></span></div>
                <div><strong>Json Config:</strong><samp id="json-config" json></samp></div>
            </div>
        </div>
    </div>
 <script>
    (function($){
        $(document).on('submit', '#dropbox-config-form', function (e) {
            e.preventDefault();
            var $this = $(this);
            var code = $this.find('#code');
            if(code.is('[required]')){
                $.post('<?= base_url('generate') ?>', $this.serialize(), function (res) {
                    $('#url-authorization').html('');
                    $('#json-config').text(JSON.stringify(res.json));
                    code.val('');
                    code.removeAttr('required').attr('disabled', true);
                }).fail(function (jqXHR, textStatus){
                    console.log(jqXHR, textStatus);
                });
            }else{
                $.post('<?= base_url('auth') ?>', $this.serialize(), function (res) {
                    $('#json-config').text('');
                    $('#url-authorization').html('<a href="'+ res.url +'" target="_blank">'+ res.url +'</a>');
                    code.removeAttr('disabled').attr('required', true);
                }).fail(function (jqXHR, textStatus){
                    console.log(jqXHR, textStatus);
                });
            }
        });
    })(jQuery);
 </script>
</body>
</html>