<h1><i class="fas fa-file-signature"></i> Termos de Uso e Política de Privacidade</h1>
<hr>

<p>Seja bem-vindo ao nosso site. Leia com bastante aten&ccedil;&atilde;o todos os termos abaixo.</p>
<p>Este documento, e todo o conte&uacute;do do site &eacute; oferecido por &Eacute; papo de Tarot, neste termo representado apenas por &ldquo;EMPRESA&rdquo;, que regulamenta todos os direitos e obriga&ccedil;&otilde;es com todos que acessam o site, denominado neste termo como &ldquo;VISITANTE&rdquo;, reguardado todos os direitos previstos na legisla&ccedil;&atilde;o, trazem as cl&aacute;usulas abaixo como requisito para acesso e visita do mesmo, situado no endere&ccedil;o http://www.epapodetarot.com.br.</p>
<p>A perman&ecirc;ncia no website implica-se automaticamente na leitura e aceita&ccedil;&atilde;o t&aacute;cita do presente termos de uso a seguir. Este termo foi atualizado pela &uacute;ltima vez em 14 de setembro de 2021.</p>
<h2>1. DA FUN&Ccedil;&Atilde;O DO SITE</h2>
<p>Este site foi criado e desenvolvido com a fun&ccedil;&atilde;o de trazer conte&uacute;do informativo de alta qualidade, a venda de produtos f&iacute;sicos, digitais e a divulga&ccedil;&atilde;o de presta&ccedil;&atilde;o de servi&ccedil;o. A EMPRESA busca atrav&eacute;s da cria&ccedil;&atilde;o de conte&uacute;do de alta qualidade, desenvolvido por profissionais da &aacute;rea, trazer o conhecimento ao alcance de todos, assim como a divulga&ccedil;&atilde;o dos pr&oacute;prios servi&ccedil;os.</p>
<p>Nesta plataforma, poder&aacute; ser realizado tanto a divulga&ccedil;&atilde;o de material original de alta qualidade, assim como a divulga&ccedil;&atilde;o de produtos de e-commerce.</p>
<p>Todo o conte&uacute;do presente neste site foi desenvolvido buscando fontes e materiais de confiabilidade, assim como s&atilde;o baseados em estudos s&eacute;rios e respeitados, atrav&eacute;s de pesquisa de alta n&iacute;vel.</p>
<p>Todo o conte&uacute;do &eacute; atualizado periodicamente, por&eacute;m, pode conter em algum artigo, v&iacute;deo ou imagem, alguma informa&ccedil;&atilde;o que n&atilde;o reflita a verdade atual, n&atilde;o podendo a EMPRESA ser responsabilizada de nenhuma forma ou meio por qualquer conte&uacute;do que n&atilde;o esteja devidamente atualizado.</p>
<p>&Eacute; de responsabilidade do usu&aacute;rio de usar todas as informa&ccedil;&otilde;es presentes no site com senso cr&iacute;tico, utilizando apenas como fonte de informa&ccedil;&atilde;o, e sempre buscando especialistas da &aacute;rea para a solu&ccedil;&atilde;o concreta do seu conflito.</p>
<h2>2.&nbsp;DO ACEITE DOS TERMOS</h2>
<p>Este documento, chamado &ldquo;Termos de Uso&rdquo;, aplic&aacute;veis a todos os visitantes do site, foi desenvolvido por&nbsp;<a href="https://diegocastro.adv.br/">Diego Castro</a>&nbsp;Advogado &ndash; OAB/PI 15.613, modificado com permiss&atilde;o para este site.</p>
<p>Este termo especifica e exige que todo usu&aacute;rio ao acessar o site da EMPRESA, leia e compreenda todas as cl&aacute;usulas do mesmo, visto que ele estabelece entre a EMPRESA e o VISITANTE direitos e obriga&ccedil;&otilde;es entre ambas as partes, aceitos expressamente pelo VISITANTE a permanecer navegando no site da EMPRESA.</p>
<p>Ao continuar acessando o site, o VISITANTE expressa que aceita e entende todas as cl&aacute;usulas, assim como concorda integralmente com cada uma delas, sendo este aceite imprescind&iacute;vel para a perman&ecirc;ncia na mesma. Caso o VISITANTE discorde de alguma cl&aacute;usula ou termo deste contrato, o mesmo deve imediatamente interromper sua navega&ccedil;&atilde;o de todas as formas e meios.</p>
<p>Este termo pode e ir&aacute; ser atualizado periodicamente pela EMPRESA, que se resguarda no direito de altera&ccedil;&atilde;o, sem qualquer tipo de aviso pr&eacute;vio e comunica&ccedil;&atilde;o. &Eacute; importante que o VISITANTE confira sempre se houve movimenta&ccedil;&atilde;o e qual foi a &uacute;ltima atualiza&ccedil;&atilde;o do mesmo no come&ccedil;o da p&aacute;gina.</p>
<h2>3. DO GLOSS&Aacute;RIO</h2>
<p>Este termo pode conter algumas palavras espec&iacute;ficas que podem n&atilde;o se de conhecimento geral. Entre elas:</p>
<ul>
<li>VISITANTE:&nbsp;Todo e qualquer usu&aacute;rio do site, de qualquer forma e meio, que acesse atrav&eacute;s de computador, notebook, tablet, celular ou quaisquer outros meios, o website ou plataforma da empresa.</li>
<li>NAVEGA&Ccedil;&Atilde;O:&nbsp;O ato de visitar p&aacute;ginas e conte&uacute;do do website ou plataforma da empresa.</li>
<li>COOKIES:&nbsp;Pequenos arquivos de textos gerados automaticamente pelo site e transmitido para o navegador do visitante, que servem para melhorar a usabilidade do visitante.</li>
<li>LOGIN:&nbsp;Dados de acesso do visitante ao realizar o cadastro junto a EMPRESA, dividido entre usu&aacute;rio e senha, que d&aacute; acesso a fun&ccedil;&otilde;es restritas do site.</li>
<li>HIPERLINKS:&nbsp;S&atilde;o links clic&aacute;veis que podem aparecer pelo site ou no conte&uacute;do, que levam para outra p&aacute;gina da EMPRESA ou site externo.</li>
<li>OFFLINE:&nbsp;Quando o site ou plataforma se encontra indispon&iacute;vel, n&atilde;o podendo ser acessado externamente por nenhum usu&aacute;rio.</li>
</ul>
<p>Em caso de d&uacute;vidas sobre qualquer palavra utilizada neste termo, o VISITANTE dever&aacute; entrar em contato com a EMPRESA atrav&eacute;s dos canais de comunica&ccedil;&atilde;o encontradas no site.</p>
<h2>4. DO ACESSO AO SITE</h2>
<p>O Site e plataforma funcionam normalmente 24 (vinte e quatro) horas por dia, por&eacute;m podem ocorrer pequenas interrup&ccedil;&otilde;es de forma tempor&aacute;ria para ajustes, manuten&ccedil;&atilde;o, mudan&ccedil;a de servidores, falhas t&eacute;cnicas ou por ordem de for&ccedil;a maior, que podem deixar o site indispon&iacute;vel por tempo limitado.</p>
<p>A EMPRESA n&atilde;o se responsabiliza por nenhuma perda de oportunidade ou preju&iacute;zos que esta indisponibilidade tempor&aacute;ria possa gerar aos usu&aacute;rios.</p>
<p>Em caso de manuten&ccedil;&atilde;o que exigirem um tempo maior, a EMPRESA ir&aacute; informar previamente aos clientes da necessidade e do tempo previsto em que o site ou plataforma ficar&aacute; offline.</p>
<p>O acesso ao site s&oacute; &eacute; permitido a maiores de 18 anos de idade ou que possu&iacute;rem capacidade civil plena. Para acesso de menores de idade, &eacute; necess&aacute;ria a expressa autoriza&ccedil;&atilde;o dos pais ou tutores, ficando o mesmo respons&aacute;veis sobre qualquer compra ou acesso efetuados pelo mesmo.</p>
<p>Caso seja necess&aacute;rio realizar um cadastro junto a plataforma, onde o VISITANTE dever&aacute; preencher um formul&aacute;rio com seus dados e informa&ccedil;&otilde;es, para ter acesso a alguma parte restrita, ou realizar alguma compra.</p>
<p>Todos os dados est&atilde;o protegidos conforme a Lei Geral de Prote&ccedil;&atilde;o de Dados, e ao realizar o cadastro junto ao site, o VISITANTE concorda integralmente com a coleta de dados conforme a Lei e com a Pol&iacute;tica de Privacidade da EMPRESA.</p>
<h2>5.&nbsp;DA LICEN&Ccedil;A DE USO E C&Oacute;PIA</h2>
<p>O visitante poder&aacute; acessar todo o conte&uacute;do do website, como artigos, v&iacute;deos, imagens, produtos e servi&ccedil;os, n&atilde;o significando nenhum tipo de cess&atilde;o de direito ou permiss&atilde;o de uso, ou de c&oacute;pia dos mesmo.</p>
<p>Todos os direitos s&atilde;o preservados, conforme a legisla&ccedil;&atilde;o brasileira, principalmente na Lei de Direitos Autorais (regulamentada na&nbsp;<a href="http://www.planalto.gov.br/ccivil_03/leis/l9610.htm">Lei n&ordm; 9.610/18</a>), assim como no C&oacute;digo Civil brasileiro (regulamentada na&nbsp;<a href="http://www.planalto.gov.br/ccivil_03/leis/2002/l10406compilada.htm">Lei n&ordm; 10.406/02</a>), ou quaisquer outras legisla&ccedil;&otilde;es aplic&aacute;veis.</p>
<p>Todo o conte&uacute;do do site &eacute; protegido por direitos autorais, e seu uso, c&oacute;pia, transmiss&atilde;o, venda, cess&atilde;o ou revenda, deve seguir a lei brasileira, tendo a EMPRESA todos os seus direitos reservados, e n&atilde;o permitindo a c&oacute;pia ou utiliza&ccedil;&atilde;o de nenhuma forma e meio, sem autoriza&ccedil;&atilde;o expressa e por escrita da mesma.</p>
<p>A EMPRESA poder&aacute; em casos concretos permitir pontualmente exce&ccedil;&otilde;es a este direito, que ser&atilde;o claramente destacados no mesmo, com a forma e permiss&atilde;o de uso do conte&uacute;do protegido. Este direito &eacute; revog&aacute;vel e limitado as especifica&ccedil;&otilde;es de cada caso.</p>
<h2>6.&nbsp;DAS OBRIGA&Ccedil;&Otilde;ES</h2>
<p>O VISITANTE ao utilizar o website da EMPRESA, concorda integralmente em:</p>
<ul>
<li>De nenhuma forma ou meio realizar qualquer tipo de a&ccedil;&atilde;o que tente invadir, hacker, destruir ou prejudicar a estrutura do site, plataforma da EMPRESA ou de seus parceiros comerciais. Incluindo-se, mas n&atilde;o se limitando, ao envio de v&iacute;rus de computador, de ataques de DDOS, de acesso indevido por falhas da mesma ou quaisquer outras forma e meio.</li>
<li>De n&atilde;o realizar divulga&ccedil;&atilde;o indevida nos coment&aacute;rios do site de conte&uacute;do de SPAM, empresas concorrentes, v&iacute;rus, conte&uacute;do que n&atilde;o possua direitos autorais ou quaisquer outros que n&atilde;o seja pertinente a discuss&atilde;o daquele texto, v&iacute;deo ou imagem.</li>
<li>Da proibi&ccedil;&atilde;o em reproduzir qualquer conte&uacute;do do site ou plataforma sem autoriza&ccedil;&atilde;o expressa, podendo responder civil e criminalmente pelo mesmo.</li>
<li>Com a Pol&iacute;tica de Privacidade do site, assim como tratamos os dados referentes ao cadastro e visita no site, podendo a qualquer momento e forma, requerer a exclus&atilde;o dos mesmos, atrav&eacute;s do formul&aacute;rio de contato.</li>
</ul>
<h2>7. DA MONETIZA&Ccedil;&Atilde;O E PUBLICIDADE</h2>
<p>A EMPRESA pode alugar ou vender espa&ccedil;os publicit&aacute;rios na plataforma, ou no site, diretamente aos anunciantes, ou atrav&eacute;s de empresas especializadas com o Adsense (<a href="https://www.google.com/">Google</a>), Taboola ou outras plataformas especializadas como o&nbsp;<a href="https://eletrocriticas.com/">Eletro Cr&iacute;ticas.</a></p>
<p>Essas publicidades n&atilde;o significam nenhuma forma de endosso ou responsabilidade pelos mesmos, ficando o VISITANTE respons&aacute;vel pelas compras, visitas, acessos ou quaisquer a&ccedil;&otilde;es referentes as estas empresas.</p>
<p>Todas as propagandas no site ou plataforma ser&atilde;o claramente destacadas como publicidade, como forma de disclaimer da EMPRESA e de conhecimento do VISITANTE.</p>
<p>Em casos de compra de produtos ou servi&ccedil;os, ser&aacute; poss&iacute;vel a devolu&ccedil;&atilde;o em at&eacute; 07 (sete) dias, conforme o C&oacute;digo de Defesa do Consumidor.</p>
<p>Estes an&uacute;ncios podem ser selecionados pela empresa de publicidade automaticamente, conforme as visitas recentes do VISITANTE, assim como baseado no seu hist&oacute;rico de busca, conforme as pol&iacute;ticas de acesso da plataforma.</p>
<h2>8.&nbsp;DOS TERMOS GERAIS</h2>
<p>O Site ir&aacute; apresentar hiperlinks durante toda a sua navega&ccedil;&atilde;o, que podem levar diretamente para outra p&aacute;gina da EMPRESA ou para sites externos.</p>
<p>Apesar da EMPRESA apenas criar links para sites externos de extrema confian&ccedil;a, caso o usu&aacute;rio acesse um site externo, a EMPRESA n&atilde;o tem nenhuma responsabilidade pelo meio, sendo uma mera indica&ccedil;&atilde;o de complementa&ccedil;&atilde;o de conte&uacute;do, ficando o mesmo respons&aacute;vel pelo acesso, assim como sobre quaisquer a&ccedil;&otilde;es que venham a realizar neste site.</p>
<p>Em caso que ocorra eventuais conflitos judiciais entre o VISITANTE e a EMPRESA, o foro elegido para a devida a&ccedil;&atilde;o ser&aacute; o da comarca da Empresa, mesmo que haja outro mais privilegiado.</p>
<p>Este Termo de uso &eacute; valido a partir de 30 de Junho de 2022.</p>
<p>&nbsp;</p>